CREATE TABLE `produtos2` (
  `CODIGO` varchar(10) NOT NULL,
  `DESCRITOR` varchar(100) DEFAULT NULL,
  `SABOR` varchar(50) DEFAULT NULL,
  `TAMANHO` varchar(50) DEFAULT NULL,
  `EMBALAGEM` varchar(50) DEFAULT NULL,
  `PRECO_LISTA` float DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ;

SELECT * FROM PRODUTOS2;

-- Inserir tudo da tabela de produtos na tabela produtos2
INSERT INTO PRODUTOS2
SELECT * FROM PRODUTOS;

UPDATE PRODUTOS2 SET PRECO_LISTA = 8;

DELETE FROM PRODUTOS2;
