SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO 
FROM tabela_de_produtos;

SELECT EMBALAGEM,
CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO' 
END AS STATUS_PRECO, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM tabela_de_produtos WHERE SABOR = 'Manga'
GROUP BY EMBALAGEM, 
CASE 
    WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
    ELSE 'PRODUTO BARATO' 
END
ORDER BY EMBALAGEM;

/* DESAFIO (CONSEGUI! SÓ ERREI NA PARTE DE COLOCAR O NOME): 
Veja o ano de nascimento dos clientes e classifique-os como: 
Nascidos antes de 1990 são velhos, nascidos entre 1990 e 1995 são jovens e 
nascidos depois de 1995 são crianças. Liste o nome do cliente e esta classificação. */
SELECT NOME,
CASE
	WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'Velhos'
    WHEN YEAR(DATA_DE_NASCIMENTO) >=1990 AND YEAR(DATA_DE_NASCIMENTO) <=1995 THEN 'Jovens'
    ELSE 'Crianças'
END AS 'Classificação por idade' 
FROM tabela_de_clientes;

